import Link from "next/link";
import { Arrow } from "@/components/Arrow";
import { pageMetadata } from "@/lib/site";
import styles from "@/components/Page.module.css";

const repository = "https://github.com/jaskevs/bld8-workbench";
export const metadata = pageMetadata("BLD8 Workbench", "Plans for a tool to inspect AI requests, sources, tool calls and cost. Workbench is currently at the documentation stage.", "/work/workbench");

export default function Workbench() {
  return <div className="container">
    <Link href="/work" className={styles.back}><span aria-hidden="true">←</span> ALL PROJECTS</Link>
    <header className={styles.projectHeader}><p className="eyebrow">01 / AI WORKFLOW TOOL</p><h1>BLD8 Workbench</h1><p className={styles.projectLead}>A planned tool for inspecting the model calls, sources, tools and cost behind an AI answer.</p><div className={styles.projectMeta}><span className={styles.projectStatus}>Planning / documentation stage</span><a href={repository} className="text-link">Repository <Arrow diagonal /></a></div></header>
    <section className={styles.projectLayout}><h2>01 / Current state</h2><div className={styles.copy}><h3>Architecture and draft decisions.</h3><p>The repository contains a proposed architecture and three draft decision records. Application development has not started.</p><p>The first use case is answering questions about a public design system. Source material is still being selected.</p></div></section>
    <section className={styles.projectLayout}><h2>02 / First version</h2><div className={styles.copy}><h3>Start with one model and a request history.</h3><p>The proposed first version uses Next.js and Node, with sign-in, request history, usage limits and a budget cap.</p><figure className={styles.architecture}><p className="eyebrow">PLANNED ARCHITECTURE</p><ol className={styles.architectureSteps}><li>Interface<span>Next.js / React</span></li><li>Request handling<span>Node / AI SDK</span></li><li>Model + storage<span>One model / Postgres</span></li></ol><figcaption>Proposed: Auth.js for sign-in; Node for limits, budgets and request history.</figcaption></figure><p>Python-based ingestion and retrieval are planned for a later stage, followed by checks against a small reference dataset.</p><a className="text-link" href={`${repository}/blob/main/docs/architecture.md`}>Architecture notes <Arrow diagonal /></a></div></section>
    <section className={styles.projectLayout}><h2>03 / Questions to try</h2><div className={styles.copy}><h3>Questions to test.</h3><p>Draft questions for the initial design-system use case.</p><ol className={styles.taskList}><li>Which component fits a particular interaction, and why?</li><li>Does a component support multi-select?</li><li>What accessibility guidance applies to dialogs?</li><li>Which token controls a particular surface’s spacing?</li><li>Which components are deprecated, and what replaces them?</li></ol></div></section>
    <section className={styles.projectLayout}><h2>04 / Draft decisions</h2><div className={styles.copy}><h3>Technical decisions.</h3><p>These records are drafts and may change during implementation.</p><div className={styles.decisions}><details><summary>001 — Hosting and deployment</summary><p>Where the application and the later retrieval service will run. <a href={`${repository}/blob/main/docs/adr/001-hosting-and-deployment.md`}>Read draft ADR 001</a>.</p></details><details><summary>002 — The Node / Python boundary</summary><p>Which work stays in Node and what belongs in the Python service. <a href={`${repository}/blob/main/docs/adr/002-node-python-boundary.md`}>Read draft ADR 002</a>.</p></details><details><summary>003 — Tool permissions</summary><p>Start with read-only tools. An approval flow is needed before tools can change anything outside the app. <a href={`${repository}/blob/main/docs/adr/003-tool-permission-model.md`}>Read draft ADR 003</a>.</p></details></div></div></section>
    <div className={styles.projectCta}><a className="button" href={repository}>View repository <Arrow diagonal /></a><Link href="/work/bld8-web" className="text-link">Website notes <Arrow /></Link></div>
  </div>;
}
